min_doc:
  image: daocloud.io/newrey/mindoc:master-3dc4dda
  privileged: false
  restart: always
  ports:
    - 8181:8181
  volumes:
    - /opt/minidoc/database:/mindoc/database
    - /opt/minidoc/uploads:/mindoc/uploads
  environment:
    - MINDOC_RUN_MODE=prod
    - MINDOC_DB_ADAPTER=sqlite3
    - MINDOC_DB_DATABASE=./database/mindoc.db
    - MINDOC_CACHE=true
    - MINDOC_CACHE_PROVIDER=file
    - MINDOC_ENABLE_EXPORT=true
    - MINDOC_EXPORT_PROCESS_NUM=2
    - MINDOC_BASE_URL=
    - MINDOC_CDN_IMG_URL=
    - MINDOC_CDN_CSS_URL=
    - MINDOC_CDN_JS_URL=
  dns:
    - 223.5.5.5
    - 223.6.6.6
